<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Superpower;
use Doctrine\ORM\EntityRepository;

/**
 * SuperpowerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SuperpowerRepository extends BaseRepository
{

}
