# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.astronaut_type:
        class: AppBundle\Form\AstronautType
        arguments: ['@doctrine']
        tags:
        - { name: form.type, alias: app_bundle_astronaut_type }
